### ISSUE TITLE
Couple of errors in overrides issues

### ISSUE THREAD

**Issue by mkorpela** [bojiang/typing_utils#5]
https://github.com/mkorpela/overrides/issues/78

https://github.com/mkorpela/overrides/issues/79

I think I need to insert this package code to overrides, if it seems there is no maintenance.
Basically the issues are now in overrides production, so I need to fix them fast.
I can move back to using this library if there is a fixing release (I can also make a PR for that).

**Comment by bojiang** [comment]
@mkorpela
Hi, thx for the feedback :)
issue 78: confirmed
issue 79: `Future[str]` is not a valid type annotation. Use `typing.Awaitable[str]` instead.

**Comment by mkorpela** [comment]
Thanks @bojiang for the response. I’ll pass the message about invalid to the reporter.
